### ISSUE TITLE
DirectGraph and FlattenStatementsHelper refactor

### ISSUE THREAD

**Issue by jaskarth** [Vineflower/vineflower#123]
`FlattenStatementsHelper` and `DirectGraph` try to represent the flow of code in a flattened way, but multiple issues with finally statements and isolated statement edges prevent it from accurately representing flow in many places. On top of this, the algorithm in `FlattenStatementsHelper` is very brittle and hard to add onto, making it difficult to make changes when needed. A refactor should make the algorithm more flexible and accurate.

See also: #108, `TestTryVar`

**Comment by SuperCoder7979** [comment]
DirectGraph has been refactored, and `TestTryVar` is fixed. #150 Fixes flatten statements helper

**Comment by jaskarth** [comment]
Because of the refactors, I think this is fine to close.
