### ISSUE TITLE
Deprecate "Max Processing Method" for removal

### ISSUE THREAD

**Issue by jaskarth** [Vineflower/vineflower#261]
With the advent of Java 20, `Thread#stop` has been deprecated for removal and will now throw `UnsupportedOperationException`. Quiltflower is affected by this change as the legacy "Max Processing Method" flag will now throw if the timeout is reached. While this won't structurally change the behavior of the decompiler, I think we should use this opportunity to remove the option all together as it is implemented rather poorly. Personally, I think if the case is that decompilation must be under a time limit, the onus should be on the caller to defer the QF task to a thread pool or such to achieve that functionality. Thoughts appreciated.

**Comment by NebelNidas** [comment]
I've been working on an async job system for Matcher over the past few months, complete with progress listeners, subjob support, thread management, job canceling, corresponding events etc. It's still missing a few minor things here and there, but it's mostly feature-complete and I've already written preliminary docs for it. You can take a look [here](https://github.com/NebelNidas/Matcher/tree/e0841f8344d5f07ef1147dcac64db225e9b9072c/src/job4j) if you're interested. I'm going to extract it into a separate repo over the next few weeks, so it can be more easily depended on.

**Comment by jaskarth** [comment]
As it's been five months with no requests to keep this option, the "max processing method" option is officially deprecated for removal in the next release.
