### ISSUE TITLE
Add heuristic for records when they don't have the acc_record flag

### ISSUE THREAD

**Issue by jaskarth** [Vineflower/vineflower#297]
There's many signs of a record being compiled, however we only use the acc_record access flag as the sign to decompile into a record. A heuristic would be desirable to better handle malformed record classes.

**Comment by zml2008** [comment]
I'm curious, does it make more sense to fix this in the decompiler, or to have a 'bytecode fixer' pass that runs before decompilation?

**Comment by MiniDigger** [comment]
thats what we do at paper, if super class is record adn acc_record isnt set, set acc_record
https://github.com/PaperMC/codebook/commit/672c7b36f092d3c632b2582a54a33c0cb8893800

**Comment by jaskarth** [comment]
We did this for 1.10.0, closing.
