### ISSUE TITLE
Weird label in decompiled class

### ISSUE THREAD

**Issue by TropheusJ** [Vineflower/vineflower#300]
Don't know exactly which version of Vineflower, I can't figure out where to find it. Whatever Quilt Loom 1.3.2 gets.
Decompiled Minecraft 1.20.1, LivingEntity#aiStep has this weird label block:
![image](https://github.com/Vineflower/vineflower/assets/60247969/9508d182-9901-4222-aa9f-0528bda453dc)

**Comment by Kroppeb** [comment]
Huh that's very strange, Vineflower should be able to see it can simplify that too an if else.

**Comment by jaskarth** [comment]
Should be fixed with [d75fd5f](https://github.com/Vineflower/vineflower/commit/d75fd5f73c4406786b82e347e7a9fd3d09401bce). Thanks for the report!
