### ISSUE TITLE
Local record is put at the end of the method, not the start

### ISSUE THREAD

**Issue by MiniDigger** [Vineflower/vineflower#314]
see TestLocalRecord#test5 (after #313 has been merged)

VF turns:
```java
  public CompletableFuture<Object> test5() {
    record R(Object a, Object b) {}
    return new CompletableFuture<>()
      .thenCombineAsync(null, R::new);
  }
```
into: 
```java
public CompletableFuture<Object> test5() {
      return new CompletableFuture().thenCombineAsync(null, (x$0, x$1) -> new R(x$0, x$1));// 35 36

      record R(Object a, Object b) {
      }

   }
```
which doesnt compile because R is referenced before its defined

**Comment by MiniDigger** [comment]
simplified test to:
```java
  public Supplier<BiFunction<Object, Object, Object>> test5() {
    record R(Object a, Object b) {}
    return () -> R::new;
  }
```
I think the issue is in NestedClassProcessor
setLocalClassDefinition tries to search all exprents for references to the classType (the record) using searchForClass, but searchForClass never finds the type because its used inside of a lambda
so searchForType somehow needs to handle lambdas

**Comment by jaskarth** [comment]
Knocking down the priority since the issue has been 'fixed'- leaving open to do the proper lambda search system
