### ISSUE TITLE
Add option to display names of lambda methods

### ISSUE THREAD

**Issue by jaskarth** [Vineflower/vineflower#331]
This would be helpful in the case of doing bytecode editing, in knowing what methods lambda code is housed in.

**Comment by tildejustin** [comment]
the example of this given in the fabric discord ([link to message](https://discord.com/channels/507304429255393322/592749519171616796/1177050827702161408)) was:
```java
private void bob() {
    //method_a
    blah.try(() -> {});
    
    blah.tryElse(/*method_b*/() -> 1, /*method_c*/() -> 2);
}
```

**Comment by jaskarth** [comment]
Done in #332.
