### ISSUE TITLE
Infinite loop in `SFormsConstructor->splitVariables`

### ISSUE THREAD

**Issue by mvisat** [Vineflower/vineflower#349]
To reproduce, compile this code `javac Dummy.java`, then decompile `java -jar vineflower.jar Dummy.class out` (or use [Dummy.zip](https://github.com/Vineflower/vineflower/files/14609003/Dummy.zip)).
```java
import java.util.Arrays;
import java.util.List;

public class Dummy {
    public static void main(String[] args) {
        method(args);
    }

    public static List<String> method(String[] args) {
        String ret = "";
        for (String arg : args) {
            try {
                switch (arg) {
                    case "a":
                        ret = "a";
                }
                break;
            } catch (Exception ex) {
            }
        }
        return Arrays.asList(ret);
    }
}
```

It will get stuck in this loop because the variable `updated` is never empty:
https://github.com/Vineflower/vineflower/blob/3482e1336de782c90a86b25d4bc6e53fed710b56/src/org/jetbrains/java/decompiler/modules/decompiler/sforms/SFormsConstructor.java#L157-L162

When I comment out this code, it won't get stuck:
https://github.com/Vineflower/vineflower/blob/3482e1336de782c90a86b25d4bc6e53fed710b56/src/org/jetbrains/java/decompiler/modules/decompiler/sforms/SFormsConstructor.java#L232-L234

**Comment by Kroppeb** [comment]
Thanks for the report! It should be fixed now.
