### ISSUE TITLE
Resugar `makeConcatWithConstants` into string templates when supported

### ISSUE THREAD

**Issue by Gaming32** [Vineflower/vineflower#377]
## Is your feature request related to a problem? Please describe.
String templates currently will decompile into the string concats they're desugared into.

## Describe the solution you'd like
If the class file supports string templates (currently Java 21+ preview class files), these string concats could be sugared into string templates. It's not guaranteed they were originally string templates, but it's impossible to tell if they were (the desugaring happens on the AST, so javac literally compiles them as if they were standard string concats).

## Additional context
<details>
<summary>Original source</summary>

```java
public class Bar {
    void foo(int x) {
        System.out.println(STR."foo: \{x}");
    }

    void bar(int x) {
        System.out.println(STR."bar: \{x}");
    }
}
```
</details>
<details>
<summary>Decompiled source (Vineflower 1.10.1)</summary>

```java
public class Bar {
   void foo(int x) {
      System.out.println("foo: " + x);
   }

   void bar(int x) {
      System.out.println("bar: " + x);
   }
}
```
</details>

**Comment by jaskarth** [comment]
I think the idea was to take a look at this after the preview phase is done, as the design of string templates is still being iterated on.

**Comment by Gaming32** [comment]
Closing due to the removal of string templates.
