### ISSUE TITLE
Unable to run on Android OS with Java Version 8 and 11

### ISSUE THREAD

**Issue by lebedynskyi** [Vineflower/vineflower#404]
## Is your feature request related to a problem? Please describe.
I tried to run vineflower on both Android versions
- Android 10 with Java below 11
- Android 13 with Java 11   (Not pure java 11.. I believe some port of this)

[Oficial description of java versions on Android OS](https://developer.android.com/build/jdks#compileSdk)

## Describe the solution you'd like
I understand that this is not a bug. It was done socially to improve development speed. But [NOT OFICIAL fern flower ](https://github.com/fesh0r/fernflower) at least works on Android 13 with Java 11. 

## Additional context
There is no exact error in what is wrong. 
- The first issue is readAllBytes and ReadN bytes in Input streams. 
- `try (final InputStream stream = StructContext.class.getResourceAsStream("StructContext.class")) {` throws null pointer

I Understand that the ticket is not full. But if Team agrees to work with it. I will provide more exact and detailed errors.

**Comment by Geolykt** [comment]
VF consciously depended on J11 for older releases (i.e. 1.10.X) and Java 17 for the current development branch. It is unlikely that this will change.
Instead (if compatibility with older java versions is strictly needed), you can try to use downgrading tools such as JvmDowngrader (<https://github.com/unimined/JvmDowngrader/>)

**Comment by lebedynskyi** [comment]
> VF consciously depended on J11 for older releases (i.e. 1.10.X) and Java 17 for the current development branch. It is unlikely that this will change (outside of the requirements getting stricter with time). Instead (if compatibility with older java versions is strictly needed), you can try to use downgrading tools such as JvmDowngrader (https://github.com/unimined/JvmDowngrader/)

I agree that it was to speed up development and make source code modern. Thats why I asked it here to clarify this point. 

Thanks for the link. Will try to investigate

**Comment by zml2008** [comment]
Vineflower requires a fully Java SE-compliant JVM that supports Java 11. That will not be changing.

**Comment by lebedynskyi** [comment]
> Vineflower requires a fully Java SE-compliant JVM that supports Java 11. That will not be changing.

Yes. I understand about java version. Maybe there is any chance to support Android with J11? 
It almost works. Now I see the issue with this method:
```

static StructClass getSentinel() {
    if (SENTINEL_CLASS == null) {
      synchronized (StructContext.class) {
        if (SENTINEL_CLASS == null) {
          try (final InputStream stream = StructContext.class.getResourceAsStream("StructContext.class")) {
            byte[] data = stream.readAllBytes();
            SENTINEL_CLASS = StructClass.create(new DataInputFullStream(data), false);
          } catch (final IOException ex) {
            throw new UncheckedIOException(ex);
          }
        }
      }
    }
    return SENTINEL_CLASS;
  }
```

On Android there is no pure class files inside application. It is inside dex file.

**Comment by McSimB** [comment]
There is a similar problem when using Java 17 and Vineflower v1.12.0.

Suggested Fix:

Provide a fallback when the  .class  resource is unavailable, e.g. by synthesizing a minimal valid classfile in memory instead of relying on  getResourceAsStream() .
