### ISSUE TITLE
[Suggestion] Add a way to inline the parameters stuff

### ISSUE THREAD

**Issue by ghost** [Vineflower/vineflower#79]
For example, QuitFlower is gonna decompile the method parameter like this if they are too long

public static Object getSomething(
  // long parameters
) {

Okay, but I would like to inline it like so

`public static Object getSomething(// long parameters) {`

so maybe add a flag for it? or if there is an existed flag for this please tell me I cant seem to find it

**Comment by jaskarth** [comment]
This is caused by the max line length parameter, which can be changed to prevent this behavior.
